#
# Kernel module make instructions go here.
#
obj-$(CONFIG_NFC_SNX0_DEVICES) += snx0.o
snx0-objs := common.o common_ese.o i2c_drv.o
ccflags-$(CONFIG_NFC_ENABLE_G7_COLD_RESET) := -DHW_COLD_RESET
#ccflags-y := -DDEBUG
#ccflags-y += -DDYNAMIC_DEBUG_MODULE
